# Generated by Django 4.1.6 on 2023-02-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="director", options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="movie", options={"ordering": ["title", "release_year"]},
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ImageField(default="default.jpg", upload_to="movie_poster"),
        ),
        migrations.AddField(
            model_name="movie",
            name="release_year",
            field=models.DateField(blank=True, null=True),
        ),
    ]
