# Generated by Django 4.1.6 on 2023-02-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_movie_rating"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="language",),
        migrations.AddField(
            model_name="movie",
            name="language",
            field=models.ManyToManyField(to="movies.language"),
        ),
    ]
